//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWindSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Version
    {
        public short Major { get; set; }
        public short Minor { get; set; }
        public short Maintenance { get; set; }
        public int Build { get; set; }
        public System.DateTime VersionDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    }
}
